# Generated by Django 2.1.7 on 2019-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profitability',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='profitability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
