# Generated by Django 2.1.7 on 2019-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_multiple',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
