# Generated by Django 2.1.7 on 2019-02-15 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0002_product_product_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityItem', models.BigIntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('profitability', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_pedidos.Client')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_pedidos.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('quantityProduct', models.BigIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pedidos.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pedidos.Product')),
            ],
        ),
    ]
