# Generated by Django 2.1.7 on 2019-03-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0002_auto_20190221_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantityProduct',
            new_name='quantity',
        ),
    ]
